/*
 * ClientApp.java
 *
 * Created on 30 December 2002, 23:50
 */

package client;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

/**
 * This is the main JApplet class. From this all other classes are derived.
 * This class also contains all displayable content.
 *
 * @author  Ken Barber
 */
public class ClientApp extends javax.swing.JApplet {
    
    private ChatAreaControl caControl;
    private UserListControl ulControl;
    private ConnectionInfo conInfo;
    private ClientConnectionControl conControl;
    private GUIControl guiControl;
    
    /** 
     * Creates new ClientApp applet. The primary part of the Gob client.
     */
    public ClientApp() {
        
        /* Set the look and feel of the GUI */
        try {
            /* Update the look and feel with the local look and feel */
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            
            /* Update any components */
            SwingUtilities.updateComponentTreeUI(this);
        } catch (Exception e) { /* There are that many exceptions that may occur, I have defaulted */
            System.out.println("Inability to set look and feel: " + e);
        } 

        /* Build all Forte generated components */
        initComponents();
        
        /* Setup both controls for the ChatArea and UserList */
        caControl = new ChatAreaControl(taMsgHistory);
        ulControl = new UserListControl(lUsers);
        
        /* Initialise the connection info object */
        conInfo = new ConnectionInfo();
        
        /* Initialise guicontrol for the conncetion thread to use */
        guiControl = new GUIControl(ulControl, caControl, bConnect, bDisconnect, lConnectionStatus, taErrorOutput, tbMain, tfUserName, tfSendPrep, pLobby);
                            
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        tbMain = new javax.swing.JTabbedPane();
        pControl = new javax.swing.JPanel();
        tfUserName = new javax.swing.JTextField();
        bDisconnect = new javax.swing.JButton();
        lUserName = new javax.swing.JLabel();
        bConnect = new javax.swing.JButton();
        lConnectionStatus = new javax.swing.JLabel();
        lHost = new javax.swing.JLabel();
        tfGobServer = new javax.swing.JTextField();
        spErrorOutput = new javax.swing.JScrollPane();
        taErrorOutput = new javax.swing.JTextArea();
        pLobby = new javax.swing.JPanel();
        bSendText = new javax.swing.JButton();
        tfSendPrep = new javax.swing.JTextField();
        spMsgHistory = new javax.swing.JScrollPane();
        taMsgHistory = new javax.swing.JTextArea();
        spUsers = new javax.swing.JScrollPane();
        lUsers = new javax.swing.JList();

        getContentPane().setLayout(null);

        tbMain.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        tbMain.setOpaque(true);
        pControl.setLayout(null);

        tfUserName.setToolTipText("Type your username here");
        tfUserName.setFocusCycleRoot(true);
        tfUserName.setAutoscrolls(false);
        tfUserName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfUserNameKeyPressed(evt);
            }
        });

        pControl.add(tfUserName);
        tfUserName.setBounds(80, 10, 220, 20);

        bDisconnect.setText("Disconnect");
        bDisconnect.setToolTipText("Click to disconnect");
        bDisconnect.setActionCommand("jButton1");
        bDisconnect.setBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.RAISED));
        bDisconnect.setEnabled(false);
        bDisconnect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bDisconnectMouseClicked(evt);
            }
        });

        pControl.add(bDisconnect);
        bDisconnect.setBounds(400, 40, 80, 20);

        lUserName.setText("Username");
        pControl.add(lUserName);
        lUserName.setBounds(10, 10, 70, 20);

        bConnect.setText("Connect");
        bConnect.setToolTipText("Click to connect");
        bConnect.setActionCommand("jButton1");
        bConnect.setBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.RAISED));
        bConnect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bConnectMouseClicked(evt);
            }
        });

        pControl.add(bConnect);
        bConnect.setBounds(400, 10, 80, 20);

        lConnectionStatus.setFont(new java.awt.Font("Dialog", 0, 12));
        lConnectionStatus.setText("Disconnected");
        lConnectionStatus.setToolTipText("Status");
        lConnectionStatus.setBorder(new javax.swing.border.EtchedBorder());
        pControl.add(lConnectionStatus);
        lConnectionStatus.setBounds(10, 70, 470, 20);

        lHost.setText("Host");
        pControl.add(lHost);
        lHost.setBounds(10, 40, 60, 15);

        tfGobServer.setEditable(false);
        tfGobServer.setToolTipText("Host to connect to");
        pControl.add(tfGobServer);
        tfGobServer.setBounds(80, 40, 220, 19);

        taErrorOutput.setEditable(false);
        taErrorOutput.setLineWrap(true);
        taErrorOutput.setDoubleBuffered(true);
        spErrorOutput.setViewportView(taErrorOutput);

        pControl.add(spErrorOutput);
        spErrorOutput.setBounds(10, 100, 470, 210);

        tbMain.addTab("Control", pControl);

        getContentPane().add(tbMain);
        tbMain.setBounds(0, 0, 500, 350);

        pLobby.setLayout(null);

        pLobby.setOpaque(false);
        bSendText.setText("Send");
        bSendText.setToolTipText("Click here to send");
        bSendText.setActionCommand("jButton1");
        bSendText.setBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.RAISED));
        bSendText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bSendTextMouseClicked(evt);
            }
        });

        pLobby.add(bSendText);
        bSendText.setBounds(426, 290, 34, 20);

        tfSendPrep.setToolTipText("Type your message here");
        tfSendPrep.setFocusCycleRoot(true);
        tfSendPrep.setAutoscrolls(false);
        tfSendPrep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfSendPrepKeyPressed(evt);
            }
        });

        pLobby.add(tfSendPrep);
        tfSendPrep.setBounds(10, 290, 410, 20);

        taMsgHistory.setEditable(false);
        taMsgHistory.setLineWrap(true);
        taMsgHistory.setWrapStyleWord(true);
        taMsgHistory.setBorder(null);
        taMsgHistory.setDoubleBuffered(true);
        taMsgHistory.setDragEnabled(true);
        spMsgHistory.setViewportView(taMsgHistory);

        pLobby.add(spMsgHistory);
        spMsgHistory.setBounds(10, 10, 380, 270);

        lUsers.setToolTipText("List of users");
        spUsers.setViewportView(lUsers);

        pLobby.add(spUsers);
        spUsers.setBounds(400, 10, 90, 270);

        getContentPane().add(pLobby);
        pLobby.setBounds(0, 0, 0, 0);

    }//GEN-END:initComponents

    private void tfUserNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfUserNameKeyPressed
        // Add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            serverConnect();
        }
    }//GEN-LAST:event_tfUserNameKeyPressed

    /** 
     * Deal with someone hitting the enter key in the SendPrep area.
     */
    private void tfSendPrepKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSendPrepKeyPressed
        // Add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            sendPreppedMessage();
        }
    }//GEN-LAST:event_tfSendPrepKeyPressed

    /**
     * Deal with someone pushing the send button.
     */
    private void bSendTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSendTextMouseClicked
        // Add your handling code here:
        sendPreppedMessage();
    }//GEN-LAST:event_bSendTextMouseClicked

    /**
     * Deal with someone hitting the disconnect button.
     */
    private void bDisconnectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bDisconnectMouseClicked
        // Add your handling code here:
        serverDisconnect();
    }//GEN-LAST:event_bDisconnectMouseClicked

    /**
     * Deal with someone hitting the connect button.
     */
    private void bConnectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bConnectMouseClicked
        // Add your handling code here:
        serverConnect();
    }//GEN-LAST:event_bConnectMouseClicked

    /**
     * Send the message typed into the PrepArea.
     */
    private void sendPreppedMessage() {
        if(tfSendPrep.getText().length() != 0) {
            conControl.sendMessage(tfSendPrep.getText());
            tfSendPrep.setText("");
        }
    }
    
    /**
     * Code to spawn a new connect thread, and connect to the server.
     */
    private void serverConnect() {
        /* Obtain username and hostname from GUI */
        conInfo.setUsername(tfUserName.getText());
        conInfo.setServer(tfGobServer.getText());
        
        /* Create a new thread object */
        conControl = new ClientConnectionControl(conInfo, guiControl);
        
        /* Start thread */
        conControl.start();
    }
    
    /**
     * Code to interrupt the connection thread.
     */
    private void serverDisconnect() {
        conControl.setInterrupt();
    }
    
    /**
     * The method first executed after the object has been initiated.
     */
    public void init() {
        /* Obtain the "host" parameter from the web page hosting the
         * applet */
        if(getParameter("host").length() > 0) {
            /* Set the host parameter as the host to connect to */
            tfGobServer.setText(getParameter("host"));
        } else {
            /* Else just default to localhost */
            tfGobServer.setText("localhost");
        }
        
        /* Focus on the username textfield */
        tfUserName.requestFocusInWindow();
    }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bConnect;
    private javax.swing.JButton bDisconnect;
    private javax.swing.JButton bSendText;
    private javax.swing.JLabel lConnectionStatus;
    private javax.swing.JLabel lHost;
    private javax.swing.JLabel lUserName;
    private javax.swing.JList lUsers;
    private javax.swing.JPanel pControl;
    private javax.swing.JPanel pLobby;
    private javax.swing.JScrollPane spErrorOutput;
    private javax.swing.JScrollPane spMsgHistory;
    private javax.swing.JScrollPane spUsers;
    private javax.swing.JTextArea taErrorOutput;
    private javax.swing.JTextArea taMsgHistory;
    private javax.swing.JTabbedPane tbMain;
    private javax.swing.JTextField tfGobServer;
    private javax.swing.JTextField tfSendPrep;
    private javax.swing.JTextField tfUserName;
    // End of variables declaration//GEN-END:variables
    
}
