/*
 * ClientApplet.java
 *
 */

package client;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

import client.controllers.*;
import client.components.*;
import client.panels.*;
import client.network.*;
import client.*;

/**
 * This is the main JApplet class. From this all other classes are initiated.
 * This class also contains all displayable content.
 *
 * @author  Ken Barber
 */
public class ClientApplet extends javax.swing.JApplet {
    
    //private MsgAreaControl maControl;
    //private UserListControl ulControl;
    private ConnectionInfo conInfo;
    public ClientConnectionControl conControl;
    public GUIControl guiControl;
    
    private String Hostname;
    
    /** 
     * Creates new ClientApp applet. The primary part of the Gob client.
     */
    public ClientApplet() {
        
        /* Set the look and feel of the GUI */
        try {
            /* Update the look and feel with the local look and feel */
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            
            /* Update any components */
            SwingUtilities.updateComponentTreeUI(this);
        } catch (Exception e) { /* There are that many exceptions that may occur, I have defaulted */
            System.out.println("Inability to set look and feel: " + e);
        } 

        /* Build all Forte generated components */
        initComponents();
        
        /* Initialise the connection info object */
        //conInfo = new ConnectionInfo();
        
        /* Create a new concontrol object */
        //conControl = new ClientConnectionControl(conInfo, guiControl);
        
        /* Obtain the "host" parameter from the web page hosting the
         * applet */
        //if(getParameter("host").length() > 0) {
            /* Set the host parameter as the host to connect to */
        
        //    Hostname = getParameter("host");
        //} else {
          /* Else just default to localhost */
        //    Hostname = "localhost";
        //}
        
        /* Initialise guicontrol for the conncetion thread to use */
        //guiControl = new GUIControl(tbMain, conControl, Hostname);        
                            
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        tbMain = new javax.swing.JTabbedPane();

        getContentPane().setLayout(null);

        setBackground(new java.awt.Color(204, 204, 255));
        setName("mainapplet");
        tbMain.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        tbMain.setFont(new java.awt.Font("Dialog", 0, 12));
        tbMain.setOpaque(true);
        getContentPane().add(tbMain);
        tbMain.setBounds(0, 0, 510, 350);

    }//GEN-END:initComponents

    /** 
     * Deal with someone hitting the enter key in the SendPrep area.
     */
    /**
     * Deal with someone pushing the send button.
     */
    /**
     * Deal with someone hitting the disconnect button.
     */
    /**
     * Deal with someone hitting the connect button.
     */
    /**
     * Send the message typed into the PrepArea.
     */
    private void sendPreppedMessage() {
        /*
        if(pLobby.tfSendPrep.getText().length() != 0) {
            conControl.sendMessage(pLobby.tfSendPrep.getText());
            pLobby.tfSendPrep.setText("");
        }
         */
    }
    
    /**
     * The method first executed after the object has been initiated.
     */
    public void init() {
        
        /* Initialise the connection info object */
        conInfo = new ConnectionInfo();
        
        guiControl = new GUIControl(tbMain, this.getParameter("host"));
        
        /* Create a new concontrol object */
        conControl = new ClientConnectionControl(this, conInfo);
        
        guiControl.displayGUI(conControl);
        
        System.out.println("End of stuff!");
        
        /* Obtain the "host" parameter from the web page hosting the
         * applet */
        //if(this.getParameter("host").length() > 0) {
            /* Set the host parameter as the host to connect to */
        
        //    pControl.tfGobServer.setText(getParameter("host"));
            //Hostname = this.getParameter("host");
        //} else {
            /* Else just default to localhost */
        //    pControl.tfGobServer.setText("localhost");
        //    Hostname = "localhost";
        //}
        
        /* Initialise guicontrol for the conncetion thread to use */
        
        
        /* Focus on the username textfield */
        //pControl.tfUserName.requestFocusInWindow();
    }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane tbMain;
    // End of variables declaration//GEN-END:variables
    
}