/*
 * ClientApplet.java
 *
 */

package client;

import client.controllers.ClientConnectionControl;
import client.controllers.GUIControl;
import client.network.ConnectionInfo;
import javax.swing.JApplet;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;


/**
 * This is the main JApplet class. From this all other classes are initiated.
 * This class also contains all displayable content.
 *
 * @author  Ken Barber
 */
public class ClientApplet extends JApplet {
    
    private ConnectionInfo conInfo;
    private ClientConnectionControl conControl;
    private GUIControl guiControl;
    private String Hostname;
    
    /** 
     * Creates new ClientApp applet. The primary part of the Gob client.
     */
    public ClientApplet() {
        
        /* Set the look and feel of the GUI */
        try {
            /* Update the look and feel with the local look and feel */
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            
            /* Update any components */
            SwingUtilities.updateComponentTreeUI(this);
        } catch (Exception e) { /* There are that many exceptions that may occur, I have defaulted */
            System.out.println("Inability to set look and feel: " + e);
        } 

        /* Build all Forte generated components */
        initComponents();
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        tbMain = new javax.swing.JTabbedPane();

        getContentPane().setLayout(null);

        setBackground(new java.awt.Color(204, 204, 255));
        setName("mainapplet");
        tbMain.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        tbMain.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        tbMain.setFont(new java.awt.Font("Dialog", 0, 12));
        tbMain.setOpaque(true);
        getContentPane().add(tbMain);
        tbMain.setBounds(0, 0, 510, 350);

    }//GEN-END:initComponents

    /**
     * The method first executed after the object has been initiated.
     */
    public void init() {
        
        /* Initialise the connection info object */
        conInfo = new ConnectionInfo();
        
        guiControl = new GUIControl(tbMain, this.getParameter("host"));
        
        /* Create a new concontrol object */
        conControl = new ClientConnectionControl(guiControl, conInfo);
        
        guiControl.displayGUI(conControl);
    }
    
    /**
     * If the applet is closed, disconnect from the server.
     */
    public void destroy() {
        conControl.serverDisconnect("Applet closed");
    }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane tbMain;
    // End of variables declaration//GEN-END:variables
    
}