/*
 * ClientApplet.java
 *
 */

package client;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

import client.components.*;
import client.panels.*;
import client.*;

/**
 * This is the main JApplet class. From this all other classes are initiated.
 * This class also contains all displayable content.
 *
 * @author  Ken Barber
 */
public class ClientApplet extends javax.swing.JApplet {
    
    private MsgAreaControl maControl;
    private UserListControl ulControl;
    private ConnectionInfo conInfo;
    private ClientConnectionControl conControl;
    private GUIControl guiControl;
    private ControlPanel pControl;
    private StatusPanel pStatus;
    private GroupChatPanel pLobby;
    
    /** 
     * Creates new ClientApp applet. The primary part of the Gob client.
     */
    public ClientApplet() {
        
        /* Set the look and feel of the GUI */
        try {
            /* Update the look and feel with the local look and feel */
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            
            /* Update any components */
            SwingUtilities.updateComponentTreeUI(this);
        } catch (Exception e) { /* There are that many exceptions that may occur, I have defaulted */
            System.out.println("Inability to set look and feel: " + e);
        } 

        setBackground(new java.awt.Color(204,204,255));
        
        /* Build all Forte generated components */
        initComponents();
        
        /* Add a control and status panel */
        
        pControl = new ControlPanel();
        pStatus = new StatusPanel();
        pLobby = new GroupChatPanel();
        
        tbMain.addTab("Control", null, pControl, "For connecting and changing username");
        tbMain.addTab("Status", null, pStatus, "A log of any server or client error messages");
                
        /* Setup both controls for the ChatArea and UserList */
        maControl = new MsgAreaControl(pLobby.taMsgHistory);
        ulControl = new UserListControl(pLobby.lUsers);
        
        /* Initialise the connection info object */
        conInfo = new ConnectionInfo();
        
        /* Initialise guicontrol for the conncetion thread to use */
        guiControl = new GUIControl(ulControl, maControl, pControl.bConnect, pControl.bDisconnect, pControl.lConnectionStatus, pStatus.taErrorOutput, tbMain, pControl.tfUserName, pLobby.tfSendPrep, pLobby);
                            
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        tbMain = new javax.swing.JTabbedPane();

        getContentPane().setLayout(null);

        setBackground(new java.awt.Color(204, 204, 255));
        setName("mainapplet");
        tbMain.setBackground(new java.awt.Color(204, 204, 255));
        tbMain.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        tbMain.setFont(new java.awt.Font("Dialog", 0, 12));
        tbMain.setOpaque(true);
        getContentPane().add(tbMain);
        tbMain.setBounds(0, 0, 510, 350);

    }//GEN-END:initComponents

    /** 
     * Deal with someone hitting the enter key in the SendPrep area.
     */
    /**
     * Deal with someone pushing the send button.
     */
    /**
     * Deal with someone hitting the disconnect button.
     */
    /**
     * Deal with someone hitting the connect button.
     */
    /**
     * Send the message typed into the PrepArea.
     */
    private void sendPreppedMessage() {
        if(pLobby.tfSendPrep.getText().length() != 0) {
            conControl.sendMessage(pLobby.tfSendPrep.getText());
            pLobby.tfSendPrep.setText("");
        }
    }
    
    /**
     * Code to spawn a new connect thread, and connect to the server.
     */
    private void serverConnect() {
        /* Obtain username and hostname from GUI */
        conInfo.setUsername(pControl.tfUserName.getText());
        conInfo.setServer(pControl.tfGobServer.getText());
        
        /* Create a new thread object */
        conControl = new ClientConnectionControl(conInfo, guiControl);
        
        /* Start thread */
        conControl.start();
    }
    
    /**
     * Code to interrupt the connection thread.
     */
    private void serverDisconnect() {
        conControl.setInterrupt();
    }
    
    /**
     * The method first executed after the object has been initiated.
     */
    public void init() {
        /* Obtain the "host" parameter from the web page hosting the
         * applet */
        if(getParameter("host").length() > 0) {
            /* Set the host parameter as the host to connect to */
            pControl.tfGobServer.setText(getParameter("host"));
        } else {
            /* Else just default to localhost */
            pControl.tfGobServer.setText("localhost");
        }
        
        /* Focus on the username textfield */
        pControl.tfUserName.requestFocusInWindow();
    }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane tbMain;
    // End of variables declaration//GEN-END:variables
    
}