/*
 * ConfigurationApp.java
 *
 * Created on 13 February 2004, 21:20
 */

/*
    Copyright (C) 2003,2004 Ken Barber
 
    This file is part of Gob Online Chat.

    Gob Online Chat is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    any later version.

    Gob Online Chat is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Gob Online Chat; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
*/

package sh.bob.gob.serverconf;

/**
 * Server Configuration
 *
 * @author  Ken Barber
 */
public class ConfigurationApp extends javax.swing.JFrame {
    
    /** Creates new form ConfigurationApp */
    public ConfigurationApp() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        pConfiguration = new javax.swing.JPanel();
        mbMain = new javax.swing.JMenuBar();
        mFile = new javax.swing.JMenu();

        setTitle("Server Configuration");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        pConfiguration.setLayout(null);

        getContentPane().add(pConfiguration, java.awt.BorderLayout.CENTER);

        mFile.setText("File");
        mbMain.add(mFile);

        setJMenuBar(mbMain);

        pack();
    }//GEN-END:initComponents
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm
    
    /**
     * 
     *
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Handle parameters from the command line 
         *
         * [ --factorydefaults <option>
         * [ --quiet ]
         * [ --outputfile <file> ] ]
         * | <file>
         * 
         * All inputs to switches that contain spaces, must be quoted (")
         *
         */
        // Arg 1: If it starts with a --factorydefaults then the next thing 
        // should be an option. Else it is an input file name, start the GUI
        // with the file.
        // 
        
        /* Run the GUI */
        new ConfigurationApp().show();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu mFile;
    private javax.swing.JMenuBar mbMain;
    private javax.swing.JPanel pConfiguration;
    // End of variables declaration//GEN-END:variables
    
}
