/*
 * RoomListPanel.java
 *
 * Created on 11 August 2003, 01:04
 */

/*
    Copyright (C) 2003,2004 Ken Barber
 
    This file is part of Gob Online Chat.

    Gob Online Chat is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    any later version.

    Gob Online Chat is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Gob Online Chat; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
*/

package sh.bob.gob.client.panels;

import sh.bob.gob.client.controllers.*;
import sh.bob.gob.client.*;
import sh.bob.gob.shared.communication.*;
import sh.bob.gob.shared.validation.*;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;


/**
 * This panel is used to list the available chat rooms.
 *
 * @author  ken
 */
public class RoomListPanel extends javax.swing.JPanel {
    
    private GUIControl guiControl;
    private ClientConnectionControl ccControl;
    
    /** Creates new form ChatPanel */
    public RoomListPanel(GUIControl gui, ClientConnectionControl ccc) {
        guiControl = gui;
        ccControl = ccc;
        
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        spRooms = new javax.swing.JScrollPane();
        lRooms = new javax.swing.JList();
        jPanel1 = new javax.swing.JPanel();
        lRoom = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        tfRoom = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        bJoinRoom = new javax.swing.JButton();
        bRefreshList = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        setBorder(new javax.swing.border.TitledBorder(null, "ROOM LIST", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11)));
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });

        spRooms.setBackground(new java.awt.Color(204, 204, 255));
        spRooms.setBorder(new javax.swing.border.EtchedBorder());
        lRooms.setBackground(new java.awt.Color(255, 255, 252));
        lRooms.setFont(new java.awt.Font("SansSerif", 1, 12));
        lRooms.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lRooms.setToolTipText("List of rooms");
        lRooms.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lRoomsMouseClicked(evt);
            }
        });

        spRooms.setViewportView(lRooms);

        add(spRooms, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.BorderLayout());

        lRoom.setFont(new java.awt.Font("SansSerif", 1, 12));
        lRoom.setText("ROOM:");
        jPanel1.add(lRoom, java.awt.BorderLayout.WEST);

        jPanel3.setLayout(new java.awt.BorderLayout());

        tfRoom.setFont(new java.awt.Font("SansSerif", 0, 12));
        tfRoom.setToolTipText("Selected room name");
        tfRoom.setFocusCycleRoot(true);
        tfRoom.setMinimumSize(new java.awt.Dimension(100, 20));
        tfRoom.setAutoscrolls(false);
        tfRoom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfRoomKeyPressed(evt);
            }
        });

        jPanel3.add(tfRoom, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel4, java.awt.BorderLayout.NORTH);

        jPanel3.add(jPanel5, java.awt.BorderLayout.SOUTH);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        bJoinRoom.setFont(new java.awt.Font("SansSerif", 1, 12));
        bJoinRoom.setText("JOIN/CREATE");
        bJoinRoom.setToolTipText("Click here to join the chosen room, or create a new room with the name specified");
        bJoinRoom.setActionCommand("jButton1");
        bJoinRoom.setBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.RAISED));
        bJoinRoom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bJoinRoomMouseClicked(evt);
            }
        });

        jPanel2.add(bJoinRoom);

        bRefreshList.setFont(new java.awt.Font("SansSerif", 1, 12));
        bRefreshList.setText("REFRESH");
        bRefreshList.setToolTipText("Click here to refresh the room list");
        bRefreshList.setActionCommand("jButton1");
        bRefreshList.setBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.RAISED));
        bRefreshList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bRefreshListMouseClicked(evt);
            }
        });

        jPanel2.add(bRefreshList);

        jPanel6.add(jPanel2);

        jPanel1.add(jPanel6, java.awt.BorderLayout.EAST);

        add(jPanel1, java.awt.BorderLayout.SOUTH);

    }//GEN-END:initComponents

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        tfRoom.requestFocus();
    }//GEN-LAST:event_formFocusGained

    private void tfRoomKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfRoomKeyPressed
        // Add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            joinRoom();
        }        
    }//GEN-LAST:event_tfRoomKeyPressed

    private void bJoinRoomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bJoinRoomMouseClicked
        // Add your handling code here:

        joinRoom();        
    }//GEN-LAST:event_bJoinRoomMouseClicked

    private void lRoomsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lRoomsMouseClicked
        // Add your handling code here:
        
        /* get the selected value */
        /* set tfRoom to this value */
        tfRoom.setText((String)lRooms.getSelectedValue());
        
    }//GEN-LAST:event_lRoomsMouseClicked

    private void bRefreshListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bRefreshListMouseClicked
        // Add your handling code here:
        RoomList rl = new RoomList();
        try {
            rl.setFilter("*");
        } catch (TextInvalidException ex) {
        }
        ccControl.sendData(rl);
    }//GEN-LAST:event_bRefreshListMouseClicked
    
    private void joinRoom() {
        /* obtain the currently selected room from tfRoom.getText */
        /* Send a command to the server to join the room */
        RoomJoin rj = new RoomJoin();
        try {
            rj.setRoomName(tfRoom.getText());
            rj.setUserName(ccControl.getConnectionInfo().getUsername());
        } catch (TextInvalidException ex) {
            guiControl.statusMessage("Invalid room name: " + ex);
            return;
        }
        ccControl.sendData(rj);
        
        RoomUserList rul = new RoomUserList();
        try {
            rul.setFilter("*");
            rul.setRoomName(tfRoom.getText());
        } catch (TextInvalidException ex) {
            guiControl.statusMessage("Invalid room name: " + ex);
            return;
        }
        ccControl.sendData(rul);
        
        RoomList rl = new RoomList();
        try {
            rl.setFilter("*");
        } catch (TextInvalidException ex) {
        }
        ccControl.sendData(rl);

        tfRoom.setText(null);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton bJoinRoom;
    public javax.swing.JButton bRefreshList;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lRoom;
    public javax.swing.JList lRooms;
    private javax.swing.JScrollPane spRooms;
    public javax.swing.JTextField tfRoom;
    // End of variables declaration//GEN-END:variables
    
}
