/*
 * StatusPanel.java
 *
 * Created on 11 August 2003, 01:04
 */

/*
    Copyright (C) 2003,2004 Ken Barber
 
    This file is part of Gob Online Chat.

    Gob Online Chat is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    any later version.

    Gob Online Chat is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Gob Online Chat; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
*/

package sh.bob.gob.client.panels;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

/**
 * This panel is used for outputting debugging and server messages, that don't
 * belong to a particular panel.
 *
 * @author  ken
 */
public class StatusPanel extends javax.swing.JPanel {
    
    /** Creates new form ChatPanel */
    public StatusPanel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        spErrorOutput = new javax.swing.JScrollPane();
        taErrorOutput = new javax.swing.JTextArea();

        setLayout(null);

        spErrorOutput.setBackground(new java.awt.Color(204, 204, 255));
        spErrorOutput.setBorder(null);
        taErrorOutput.setBackground(new java.awt.Color(252, 255, 252));
        taErrorOutput.setEditable(false);
        taErrorOutput.setLineWrap(true);
        taErrorOutput.setBorder(null);
        taErrorOutput.setDoubleBuffered(true);
        spErrorOutput.setViewportView(taErrorOutput);

        add(spErrorOutput);
        spErrorOutput.setBounds(0, 0, 510, 324);

    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane spErrorOutput;
    public javax.swing.JTextArea taErrorOutput;
    // End of variables declaration//GEN-END:variables
    
}
