#!/bin/bash

# This script is responsbile for backgrounding the server java app
#

JAVACMD=$JAVA_HOME/bin/java
SERVJAR=/usr/share/java/gob/server.jar
LOGDIR=/var/log/gob
CONFIG=/etc/gobd/gobd.conf.xml

if [ ! -f $JAVACMD ] ; then
    echo "I cannot find java! Is JAVA_HOME set? Try setting it in the SysV script."
    exit 1
fi

if [ ! -f $SERVJAR ] ; then
    echo "I cannot find server.jar: $SERVJAR"
    exit 1
fi

if [ ! -d $LOGDIR ] ; then
    echo "I cannot find the logging directory: $LOGDIR"
    exit 1
fi

( $JAVACMD -jar $SERVJAR $CONFIG >> /dev/null 2>&1 ) &
