::msgcat::mcmset en {
.popup,Text
{This will install <AppName> on your computer.  Continue?}

.background,Text
<AppName>

.setup,Caption
{Setup is preparing the InstallBase Install Wizard which will guide you through the rest of the setup process.  Please wait.}

.welcome,Caption
{Welcome to the <AppName> Setup program.  This program will install <AppName> on your computer.}

.welcome,Text
{It is strongly recommended that you exit all Windows programs you have running.  Click Next to continue with the Setup program.


WARNING: This program is protected by copyright law and international treaties.

Unauthorized reproduction or distribution of this program, or any portion of it, may result in severe civil and criminal penalties, and will be prosecuted to the maximum extent possible under law.}

.welcome,BackButton
{< Back}

.welcome,NextButton
{Next >}

.welcome,CancelButton
Cancel

.license,Caption
{Please read the following License Agreement.  Press the PAGE DOWN key to see the rest of the agreement.}

.license,Text
{Do you accept all the terms of the preceding License Agreement?  If you choose No, Setup will close.  To install <AppName>, you must accept this agreement.}

.license,Info
{Put your license agreement here.}

.license,AcceptCheck
{I accept the terms of this license agreement.}

.license,NextButton
Yes

.license,BackButton
{< Back}

.license,CancelButton
No

.readme,Info
{Put your readme information here.}

.readme,NextButton
{Next >}

.readme,BackButton
{< Back}

.readme,CancelButton
Cancel

.userInfo,Caption
{Type your name below.  You must also type the name of the company you work for and the product serial number.}

.userInfo,NextButton
{Next >}

.userInfo,BackButton
{< Back}

.userInfo,CancelButton
Cancel

.destLoc,Caption
{Setup will install <AppName> in the following folder.

To install to this folder, click Next.

To install to a different folder, click Browse and select another folder.

You can choose not to install <AppName> by clicking Cancel to exit Setup.}

.destLoc,NextButton
{Next >}

.destLoc,BackButton
{< Back}

.destLoc,CancelButton
Cancel

.destLoc,BrowseButton
Browse

.setupType,Caption
{Click the type of Setup you prefer, then click Next.}

.setupType,NextButton
{Next >}

.setupType,BackButton
{< Back}

.setupType,CancelButton
Cancel

.customSetup,Caption
{Select the components you want to install, clear the components you do not want to install.}

.customSetup,NextButton
{Next >}

.customSetup,BackButton
{< Back}

.customSetup,CancelButton
Cancel

.selectFolder,Caption
{Setup will add the program icons to the Program Folder listed below.  You may type a new folder name, or select from the existing Folders list.  Click Next to continue.}

.selectFolder,NextButton
{Next >}

.selectFolder,BackButton
{< Back}

.selectFolder,CancelButton
Cancel

.startCopy,Caption
{Setup has enough information to start copying the program files.  If you want to review or change any settings, click Back.  If you are satisfied with the settings, click Next to begin copying files.}

.startCopy,Text
{Install Directory:
	<InstallDir>

Setup Type:
	<InstallType>}

.startCopy,NextButton
{Next >}

.startCopy,BackButton
{< Back}

.startCopy,CancelButton
Cancel

.copyFiles,Caption
{Installing <AppName> files}

.copyFiles,CancelButton
Cancel

.setupComplete,Caption
{Setup has finished installing <AppName> on your computer.

Setup can launch the Read Me file and <AppName>.  Choose the options you want below.}

.setupComplete,Text
{Click Finish to complete Setup.}

.setupComplete,LaunchButton
{Yes, I want to launch <AppName> now.}

.setupComplete,ReadmeButton
{Yes, I want to view the Read Me file.}

.setupComplete,DesktopButton
{Create a shortcut for <AppName> on my Desktop.}

.setupComplete,NextButton
{Next >}

.setupComplete,BackButton
{< Back}

.setupComplete,CancelButton
Finish

.exitSetup,Caption
{Setup is not complete.  If you quit now, <AppName> will not be installed.

You may run Setup at a later time to complete the installation.

Do you wish to resume installing <AppName>?}

.exitSetup,YesButton
Yes

.exitSetup,NoButton
No

}
