::msgcat::mcmset en {
.uninstallPopup,Caption
{This will completely remove <AppName> from your system.  Are you sure you want to do this?}

.uninstallCompleteRemoval,Caption
{Some components could not be removed.  Do you wish to delete them anyway (not recommended)?}

.uninstallComplete,Caption
{Uninstall Completed Successfully.}

.uninstallComplete,CancelButton
Finish

.uninstallErrors,Caption
{Uninstall Completed Successfully.

Some components could not be removed.}

.uninstallErrors,NextButton
Details

.uninstallErrors,CancelButton
Finish

.uninstallDetails,Caption
{The following errors occurred during uninstall:}

.uninstallDetails,Errors
<Errors>

.uninstallDetails,CancelButton
Finish

}
