/*
 * GroupChatPanel.java
 *
 * Created on 11 August 2003, 01:04
 */

package client.panels;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

/**
 *
 * @author  ken
 */
public class GroupChatPanel extends javax.swing.JPanel {
    
    /** Creates new form ChatPanel */
    public GroupChatPanel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        bSendText = new javax.swing.JButton();
        tfSendPrep = new javax.swing.JTextField();
        spMsgUsers = new javax.swing.JSplitPane();
        spMsgHistory = new javax.swing.JScrollPane();
        taMsgHistory = new javax.swing.JTextArea();
        spUsers = new javax.swing.JScrollPane();
        lUsers = new javax.swing.JList();

        setLayout(null);

        bSendText.setFont(new java.awt.Font("Dialog", 0, 12));
        bSendText.setText("Send");
        bSendText.setToolTipText("Click here to send");
        bSendText.setActionCommand("jButton1");
        bSendText.setBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.RAISED));
        bSendText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bSendTextMouseClicked(evt);
            }
        });

        add(bSendText);
        bSendText.setBounds(465, 300, 40, 23);

        tfSendPrep.setToolTipText("Type your message here");
        tfSendPrep.setFocusCycleRoot(true);
        tfSendPrep.setAutoscrolls(false);
        tfSendPrep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfSendPrepKeyPressed(evt);
            }
        });

        add(tfSendPrep);
        tfSendPrep.setBounds(0, 300, 465, 24);

        spMsgUsers.setBackground(new java.awt.Color(204, 204, 255));
        spMsgUsers.setBorder(null);
        spMsgUsers.setDividerLocation(400);
        spMsgUsers.setDividerSize(1);
        spMsgUsers.setContinuousLayout(true);
        spMsgUsers.setDoubleBuffered(true);
        spMsgHistory.setBackground(new java.awt.Color(204, 204, 255));
        taMsgHistory.setEditable(false);
        taMsgHistory.setLineWrap(true);
        taMsgHistory.setWrapStyleWord(true);
        taMsgHistory.setBorder(null);
        taMsgHistory.setDoubleBuffered(true);
        taMsgHistory.setDragEnabled(true);
        spMsgHistory.setViewportView(taMsgHistory);

        spMsgUsers.setLeftComponent(spMsgHistory);

        spUsers.setBackground(new java.awt.Color(204, 204, 255));
        lUsers.setToolTipText("List of users");
        spUsers.setViewportView(lUsers);

        spMsgUsers.setRightComponent(spUsers);

        add(spMsgUsers);
        spMsgUsers.setBounds(1, 2, 504, 298);

    }//GEN-END:initComponents

    private void tfSendPrepKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSendPrepKeyPressed
        // Add your handling code here:
    }//GEN-LAST:event_tfSendPrepKeyPressed

    private void bSendTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSendTextMouseClicked
        // Add your handling code here:
    }//GEN-LAST:event_bSendTextMouseClicked
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton bSendText;
    public javax.swing.JList lUsers;
    private javax.swing.JScrollPane spMsgHistory;
    private javax.swing.JSplitPane spMsgUsers;
    private javax.swing.JScrollPane spUsers;
    public javax.swing.JTextArea taMsgHistory;
    public javax.swing.JTextField tfSendPrep;
    // End of variables declaration//GEN-END:variables
    
}
