/*
 * PrivChatPanel.java
 *
 * Created on 11 August 2003, 01:04
 */

package client.panels;

import client.controllers.*;
import client.*;
import client.components.*;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

/**
 * The PrivChatPanel is for individual one-on-one chat.
 *
 * @author  ken
 */
public class PrivChatPanel extends javax.swing.JPanel {
    
    private GUIControl guiControl;
    private ClientConnectionControl ccControl;
    private String userName;
    private MsgAreaControl msgAreaControl;    
    
    /** Creates new form ChatPanel */
    public PrivChatPanel(GUIControl gui, ClientConnectionControl ccc, String name) {
        guiControl = gui;
        ccControl = ccc;
        userName = name;        
        
        initComponents();
        
        msgAreaControl = new MsgAreaControl(taMsgHistory);        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        bSendText = new javax.swing.JButton();
        tfSendPrep = new javax.swing.JTextField();
        spMsgHistory = new javax.swing.JScrollPane();
        taMsgHistory = new javax.swing.JTextArea();
        bClose = new javax.swing.JButton();

        setLayout(null);

        bSendText.setFont(new java.awt.Font("Dialog", 0, 12));
        bSendText.setText("Send");
        bSendText.setToolTipText("Click here to send");
        bSendText.setActionCommand("jButton1");
        bSendText.setBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.RAISED));
        bSendText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bSendTextMouseClicked(evt);
            }
        });

        add(bSendText);
        bSendText.setBounds(465, 300, 40, 23);

        tfSendPrep.setToolTipText("Type your message here");
        tfSendPrep.setFocusCycleRoot(true);
        tfSendPrep.setAutoscrolls(false);
        tfSendPrep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfSendPrepKeyPressed(evt);
            }
        });

        add(tfSendPrep);
        tfSendPrep.setBounds(0, 300, 465, 24);

        spMsgHistory.setBackground(new java.awt.Color(204, 204, 255));
        taMsgHistory.setEditable(false);
        taMsgHistory.setLineWrap(true);
        taMsgHistory.setWrapStyleWord(true);
        taMsgHistory.setBorder(null);
        taMsgHistory.setDoubleBuffered(true);
        taMsgHistory.setDragEnabled(true);
        spMsgHistory.setViewportView(taMsgHistory);

        add(spMsgHistory);
        spMsgHistory.setBounds(0, 20, 506, 280);

        bClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bCloseMouseClicked(evt);
            }
        });

        add(bClose);
        bClose.setBounds(6, 4, 12, 12);

    }//GEN-END:initComponents

    private void bCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCloseMouseClicked
        // Add your handling code here:
        guiControl.getPrivTabControl().removeUser(userName);
    }//GEN-LAST:event_bCloseMouseClicked

    private void tfSendPrepKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSendPrepKeyPressed
        // Add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            sendMessage();
        }
    }//GEN-LAST:event_tfSendPrepKeyPressed

    private void bSendTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSendTextMouseClicked
        // Add your handling code here:
        sendMessage();        
    }//GEN-LAST:event_bSendTextMouseClicked
    
    private void sendMessage() {
        ccControl.sendCommand("usersend:" + userName + ":" + tfSendPrep.getText());
        tfSendPrep.setText("");
        tfSendPrep.requestFocus();
    }    
    
    public void writeUserMessage(String name, String message) {
        msgAreaControl.userMessage(name, message);
    }
    
    public void writeStatusMessage(String message) {
        msgAreaControl.statusMessage(message);
    }    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bClose;
    public javax.swing.JButton bSendText;
    private javax.swing.JScrollPane spMsgHistory;
    public javax.swing.JTextArea taMsgHistory;
    public javax.swing.JTextField tfSendPrep;
    // End of variables declaration//GEN-END:variables
    
}
